# Behaviour model
string model         # Base58 
# Task
string objective     # Base58
# Operational token
string token         # address
# Execution cost
uint32 cost          # int
# Execution count
uint32 count         # int
# Validator network address
string validator     # address
# Validator network fee
uint32 validatorFee  # int 
# Order salt
uint8[] salt         # hex 
# Order signature
uint8[] signature    # hex
# Deadline block number
uint32 deadline      # int
